# Generated by Django 6.0.1 on 2026-01-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("product_code", models.CharField(max_length=50, unique=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "sale_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=100, null=True)),
                ("memory", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "manufacturer",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("reviews_count", models.IntegerField(default=0)),
                (
                    "display_size",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "screen_resolution",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("images", models.JSONField()),
                ("characteristics", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
