# Generated by Django 6.0.1 on 2026-01-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="currency",
            field=models.CharField(default="₴", max_length=5),
        ),
    ]
